[tox]
envlist =
    lint
    tests

[testenv]
passenv = *
lint_folders =
    "{toxinidir}/examples" \
    "{toxinidir}/src" \
    "{toxinidir}/tests"

[testenv:tests]
description = Run ALL test suite with pytest and {basepython}.
usedevelop = true
deps = 
    pytest
    pytest-cov

commands = pytest {posargs}

[testenv:tests-min]
description = Run the minimal core tests with pytest and {basepython}.
usedevelop = true
deps = -r tests/requirements.txt

commands = pytest {posargs}

[testenv:lint]
description = Run linters and type checks
package = skip
deps = ruff
commands =
    ruff format --diff {[testenv]lint_folders}
    ruff check {[testenv]lint_folders}

[testenv:examples]
description = Run examples as smoke tests.
usedevelop = true
commands =
    python examples/calculator/example.py
    bash -c 'cd examples/train-mlp && DATASETS=. python prepare.py && cd my_experiment && DATASETS=.. lorem-train'
    bash -c 'cd examples/train-bec && DATASETS=. python prepare.py && cd my_experiment && DATASETS=.. lorem-train'

allowlist_externals = bash

[testenv:format]
description = Abuse tox to do actual formatting on all files.
package = skip
deps = ruff
commands =
    ruff format {[testenv]lint_folders}
    ruff check --fix-only {[testenv]lint_folders} {posargs}
